### ISSUE TITLE
Run attributeChangedCallback synchronously

### ISSUE THREAD

**Issue by cronon** [WebReflection/document-register-element#106] opened 2017-05-24 11:19 UTC
https://jsfiddle.net/8a50rx17/4
```js
<x-tag x="1"></x-tag>

customElements.define('x-tag', class extends HTMLElement {
  static get observedAttributes(){
  return ['x']
  }
  attributeChangedCallback(attr, old, value){
     console.log(attr, value)
  }
})
customElements.whenDefined('x-tag').then(() => {
  document.querySelector('x-tag').setAttribute('x','2')
  console.log('value changed')
  document.querySelector('x-tag').setAttribute('x','3')
  console.log('value changed')
})
```
Expected (as in Chrome):
x 1
x 2
value changed
x 3
value changed

Actual:
x 1
value changed
value changed
x 3
x 3

**Comment by WebReflection** [comment] 2017-05-24 11:22
the "Actual" in which browser?

If it's one of those that fallbacks to MutationObserver it's a won't fix ('cause I cannot)

**Comment by cronon** [comment] 2017-05-24 11:33
In firefox 53.0.2

Unfortunately, it's not a typo :(

**Comment by WebReflection** [comment] 2017-05-24 11:38
right ... I might be able to fix the missing correct value for the `2` but I won't be able to anything about the synchronous notification 'cause I'm sure FF uses MutationObserver which AFAIK is always async.

Would that work for you?

**Comment by cronon** [comment] 2017-05-24 12:03
that would be nice, thanks

**Comment by cronon** [comment] 2017-05-24 12:41
just checked it
Works as expected in IE

**Comment by WebReflection** [comment] 2017-05-24 13:06
IE doesn't use MutationObserver but synchronous DOMAttrChanged event

**Comment by WebReflection** [comment] 2017-05-24 18:07
OK, turns out this is a limitation of the MutationObserver that doesn't carry the set value, only the old one.

The cost of implementing an indexOf based filter to avoid duplicated new values doesn't seem to be worth it and in any case it won't be synchronous.

Since for years this hasn't been a problem for all major projects out there based on this polyfill, I think I'll flag this as caveat/won't fix in the README.

### Workaround

As ugly as it looks, if this stuff is so important for your project, you might decide to opt out from MutationObserver putting this script on top of your page:
```html
<script>var _MO=window.MutationObserver;delete window.MutationObserver;</script>
<script src="document-register-element.js"></script>
<script>window.MutationObserver=_MO</script>
```

This works already in FF and won't change anything in IE.
It shouldn't affect Safari or Chrome at all.

Apologies if the solution is not ideal.

**Closed** 2017-07-24 10:45 UTC

**Comment by tomalec** [comment] 2017-08-20 18:28
@WebReflection What is the cost of opting out from Mutation Observer?
It would be cool to have this issue (async `attributeChangedCallback`) listed in README caveats, preferably with the hint above.

**Comment by WebReflection** [comment] 2017-08-20 21:03
> What is the cost of opting out from Mutation Observer?

Mutation Observer was born to address issues with [mutation events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Mutation_events)

> This feature has been removed from the Web standards. Though some browsers may still support it, it is in the process of being dropped. Avoid using it and update existing code if possible;
> Mutation events provide a mechanism for a web page or an extension to get notified about changes made to the DOM. Use Mutation Observers instead if possible.

On top of that ...

> Adding DOM mutation listeners to a document profoundly degrades the performance of further DOM modifications to that document (making them 1.5 - 7 times slower!). Moreover, removing the listeners does not reverse the damage.


Answering the rest ...

> It would be cool to have this issue (async attributeChangedCallback) listed in README caveats

I might add that, sure

> preferably with the hint above.

I don't want to promote worst practices so less people know about a work-around, better it is for the same browsers they are targeting.

Like I've said, this hasn't been an issue for the last 4 years now, just react to `attributeChangedCallback` whenever it happens and that's it?

**Comment by tomalec** [comment] 2017-08-21 15:49
Thanks for quick and elaborate answer!

I hope it will work for me as well, but it was quite unexpected behavior that broke most of my tests.

**Comment by tomalec** [comment] 2017-09-04 19:46
Unfortunately, it seems it breaks the functionality of my element, that for last 4yrs was strictly synchronous (https://github.com/Juicy/juicy-html).

>  just react to `attributeChangedCallback` whenever it happens and that's it?

I'm not sure if I get what you propose here.
The example use case for my element is:
```js
juicyHtml.setAttribute('content', '/path/to/file.html'); // this sends a XHR
juicyHtml.pending.addEventListener('progress', updateExternalPreloader); // with this polyfill `pending` request is still `undefined` still undefined
```

How then a consumer of 'juicy-html' should "react to `attributeChangedCallback`"?

**Comment by WebReflection** [comment] 2017-09-04 20:02
so ... you set an attribute and you expect that automagically, only if the thing is attached, a wild `pending` property appears that points to the XHR ?

Maybe this is a better pattern?
```js
oReq.onprogress = function(event) {
  that.dispatchEvent(event);
};

// so that ...
juicyHtml.setAttribute('content', '/path/to/file.html');
juicyHtml.addEventListener('progress', updateExternalPreloader);
```

???

Anyway, this is **not** going to be fixed in here.

**Comment by tomalec** [comment] 2017-09-05 00:51
Yes, that's basically all that this element does. Once you set an attribute, it creates a XHR, then stamps it's response to the DOM and in the meantime exposes the request to the user via `.pending`, allowing him/her to listen to native events, abort it, etc.

So it seems I'd have to either forward entire API (`dispatchEvent` for onload, onprogres,.., add `abort` method & co., etc.) what seems like an overhead for me or just do `this.dispatchEvent('attribute-changed')` in `attributeChangedCallback` what looks hacky.

I will check how far I can go with https://github.com/webcomponents/custom-elements/pull/88, as it seems to work synchronously.

Thanks for support and clear picture of how it works (and will work) :)

**Comment by WebReflection** [comment] 2017-09-05 01:03
beside the issue ou are having in here ... this is IMO a not so good API

> Once you set an attribute, it creates a XHR, then stamps it's response to the DOM and in the meantime exposes the request to the user via .pending, allowing him/her to listen to native events, abort it, etc.

Look at this code, it makes no logical sense if you don't know what is this about:
```js
juicyHtml.setAttribute('content', '/path/to/file.html');
juicyHtml.pending.addEventListener('progress', updateExternalPreloader);
```

**why** ???

I mean, with custom elements you can just have a special property that doesn't even need to trigger an attribute change (but it could).

```js
juicyHtml.content =  '/path/to/file.html';
juicyHtml.pending.addEventListener('progress', updateExternalPreloader);
```

This is already better. It doesn't mess up with the DOM just have an attributeChangedCallback, 'cause if you are complaining about forwarding events, here you are using events just to forward an XHR, and yet that API makes no sense if somebody doesn't explain it to you.

This one though:
```js
const loader = juicyHtml.setContent('/path/to/file.html');
loader.addEventListener(....);
```

makes way more sense. What is `pending` after all? It's a property that if the element is not even there doesn't exist. Pending for what? Why an XHR has been renamed to pending? once it's loaded is it still called pending?

I hope you got my 2 cents FWIW, good luck with any other polyfill you can find out there.

**Comment by tomalec** [comment] 2017-09-05 10:30
Ha! I like this approach. :tada:

We are using property setters in most of our element, in this case, we are not, as it collides with native `content` property of `<template>`. That was a separate issue that we were going to clean up. Just migration to V1 was more urgent.

Now, I see that making a setter would solve my original case. As 
```js
juicyHtml.content =  '/path/to/file.html'; // a "setter", easy-peasy
juicyHtml.pending.addEventListener('progress', updateExternalPreloader);
```
works exactly as before and would require simple replace in user's code, while old `.setAttribute` will still work simmilar, but just async.

You're right. I start to feel, I made this `pending` an exposed implementation details rather than intuitive API. Luckily, thanks to what's stated above, I can make API clarification a next, separate step after CEv1 migration.

Thanks a lot for your feedback and comments!
