### ISSUE TITLE
Always hitting v1 polyfill case in Chrome

### ISSUE THREAD

**Issue by cramforce** [WebReflection/document-register-element#110] opened 2017-06-09 23:55 UTC
It appears that this always throws in Chrome
https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L982

…and so `polyfillV1()` is always called. I tested this in current stable and canary.

Is this intended?

**Comment by WebReflection** [comment] 2017-06-29 22:55
Sorry I'm late @cramforce , here the answer:

Chrome fails at creating builtin extends, so it's expected to be patched and fallback to V0 **only** when it comes to native builtin extends.

It's in the specs, and until I have specs saying you can register an extend and use it like a native one, I'll have every browser patched 'till they get it right.

Does this answer your question?

**Comment by WebReflection** [comment] 2017-07-23 11:22
Hey @cramforce , what do you think about a version of this poly that doesn't implement custom element V1 builtins at all ?

**Comment by cramforce** [comment] 2017-07-24 02:31
I think I like it, but not sure I understand what that actually means :)

**Comment by WebReflection** [comment] 2017-07-24 10:42
Let me try to explain.

This polyfill patches many things to be as compliant as possible with the current [Custom Element specifications](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements).

The spec includes [Creating a customized built-in element](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-customized-builtin-example) which is about using the infamous third argument:
```js
customElements.define(
  "plastic-button",
  PlasticButton,
  { extends: "button" }
);
```
So that the output will be, per each new instance, as such:
```html
<button is="plastic-button">Click Me!</button>
```

### The Problem

Even if it's been working well since ever, and it was part of the **V0** version of the API,
Apple/WebKit developers said they have no intention to implement that functionality.

**We are stuck** with a specification that lies because **not even latest Chrome V1** works like that.


### The Proposal

Every browser right now needs to be patched because of the polyfill attempt to featre detect that part of the specification that no browser vendor wants to implement.

The result is some overhead in terms of both code and/or native features hidden behind the scene, so that you see that Chrome code is not the native one and it's partially patched due built-ins issue.


### As Summary

I am thinking to rewrite this polyfill in a major version where I'll completely ditch V0 API and I'll polyfill only V1 **without** custom builtins support.

That means no migration pattern, no V0 compatibility, either it uses basic native V1 or it patches the browser to fallback and use V1 only (so, again, getting rid of V0).

However, I don't have numbers to understand how important is to keep fallback in old V0.

AFAIK only Chrome shipped that, but Chrome is also evergreen so I think no Chrome today has V0 but **not** V1.

Am I right? Does any of this make sense?

**Comment by MikeVaz** [comment] 2017-07-24 13:01
We use it now. So I am voting to keep it there. I think in next 5 years something might shift in terms of specs and in approach to extend native elements. But it also might be a time we wouldn't need to polyfill custom elements

**Comment by WebReflection** [comment] 2017-07-24 13:18
Fair enough. Then I think we can close this since Chrome failing the V1 custom built in failing back to V0 custom built in is expected.

**Comment by WebReflection** [comment] 2017-07-24 13:18
falling *

**Comment by cramforce** [comment] 2017-07-24 13:49
We certainly don't need the built-in extension feature. At the very least, it may make sense to make the feature detection (that never detects anything) optional.

**Comment by WebReflection** [comment] 2017-07-24 13:51
what do you mean by

> that never detects anything

? If it's that no browser would ever be successful there then I agree, optional might be a better option.

**Comment by cramforce** [comment] 2017-07-24 13:56
Yeah, I meant, that it isn't current expected to ever detect the feature, since no browser ships it.

**Comment by WebReflection** [comment] 2017-07-24 14:33
Please let me know if `v1.6` is sufficient to solve this issue.

Quick info and instructions in the updated README:
https://github.com/WebReflection/document-register-element#avoiding-ce-built-in

**Comment by MikeVaz** [comment] 2017-07-24 14:38
It looks like Chromium team is making some progress there https://bugs.chromium.org/p/chromium/issues/detail?id=618606 

I wounder what Opera team has implemented? Do you know? Firefox in progress and Edge is still in consideration. So it is not certain who will support this. But if all the browsers would support it except Safari this would put some pressure on Webkit team to make it happen. 

Alternatively if nobody would support it then spec could change to remove it.

**Comment by WebReflection** [comment] 2017-07-24 14:41
I think current update solves all the cases ... if you don't need V1 custom built-in there's no reason to have the whole env patched so if Malte is happy with latest, I'm happy too, nobody loses.

It's just about using the pony version, instead of the global / CDN module

**Comment by cramforce** [comment] 2017-07-24 15:56
Is this expected to also remove the workaround for allowing inheritance from HTMLElement using transpiled classes?

**Comment by WebReflection** [comment] 2017-07-24 16:09
P.S. in any case, this is surely something I need to highlight on the README page cause I'm quite sure everyone will fall after Babel.

**Comment by WebReflection** [comment] 2017-07-29 09:38
Hey @cramforce , give this a try:
https://github.com/babel/babel/issues/4480#issuecomment-318817038

It fixed all the issues for me, you need to double check on your target browsers though, there is quite some difference if the `Reflect` object is not available or it's wrongly polyfilled.

Cheers

**Comment by cramforce** [comment] 2017-07-31 03:28
@WebReflection Working on it. Just need to find the time to clean it up.

**Comment by WebReflection** [comment] 2017-09-20 15:39
any update?

**Comment by cramforce** [comment] 2017-09-20 17:32
Sorry, for slow progress. Just this week managed to finally upgrade babel
and can move forward with this.

On Wed, Sep 20, 2017 at 8:39 AM, Andrea Giammarchi <notifications@github.com

**Comment by WebReflection** [comment] 2017-09-28 15:15
> Is there a latest version of a non ES6 class that can inherit from built-ins? 

I am not sure I understand this question

> I think we need that anyway unless we want to port the plugin to Closure Compiler.

I don't know how/what/why you are transpiling code but if you use CC to produce an output then last option you mentioned seems to be the best to me.

**Comment by cramforce** [comment] 2017-09-28 15:18
What I meant was whether you had an example handy for how the transpiled output looks like (so I can copy it into the source directly). If not I'll just go ahead and look at the source of the plugin.

**Comment by WebReflection** [comment] 2017-09-28 15:25
this is the template:
https://github.com/WebReflection/babel-plugin-transform-builtin-classes/blob/master/src/index.js#L4-L30

basically, if the parser encounters a class that is extending a known native one, [if found in this list](https://github.com/WebReflection/babel-plugin-transform-builtin-classes/blob/master/.babelrc#L7-L536), it wraps it and returns the class passed to `fixBabelExtend`

**Comment by trusktr** [comment] 2017-10-06 22:08
`noBuiltIn: true` FTW!

Use [custom-attributes](https://github.com/matthewp/custom-attributes) instead, or [element-behaviors](https://github.com/w3c/webcomponents/issues/662) once I've polyfilled it (soon, as I'm going to use it in a project).

**Closed** 2018-05-31 12:47 UTC

**Comment by WebReflection** [comment] 2018-05-31 12:50
@cramforce since Chrome 67 shipped native custom elements builtin support I've fixed my features detection and updated this polyfill so that native support won't ever be affected by this poly.

  * why on earth nobody informed me about this ? https://blog.revillweb.com/extending-native-dom-elements-with-web-components-233350c8e86a
  * why on earth `ce.getElement('is') === null` even if `el.outerHTML` shows the `is` attribute ?

Anyway, I can happily close this long standing issue 🎉

**Comment by MikeVaz** [comment] 2018-05-31 14:54
Did anybody tried if properly [transpiled](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=PTAEFMA8BdwOwCYGdRIPYFtygQSwGb7gBO80ocAhtLgG7YDGacS0xArg9GsQFAMAbSkhQBZAJ4AhdtG5wIMeMlAAJACqiAMtNnMAogPBY45AN4BfXrxA5w-XHGy5ySAA7gGBcQ4DmoAO4AFtQA5ChQsIi-_OysmAZGZEgAdAh2DuAAFCEY4gC0AEYyciEANKASOnLlphFKSABcoCFFunAh5gCUANxWNgA8rXKguEgAvABEuYXFzBMAfIK4DADWoFj9wEPM87wIaAzsxtDJBWgI4smUru6IAMKBuAIImbygFOD-FVKzcLydyVgMDuzEi5DGzSWq3W4BCvSAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&lineWrap=true&presets=es2015%2Cstage-0&prettier=false&targets=&version=6.26.0&envVersion=1.6.2) code would work without a polyfill?

**Comment by WebReflection** [comment] 2018-05-31 15:20
> Did anybody try if properly transpiled code would work without a polyfill?

it doesn't (Custom Elements is not just a transpilation thing, it's a whole specification) and also only latest babel might work as expected.

**Comment by WebReflection** [comment] 2018-05-31 15:21
@MikeVaz unless you are talking about Chrome 67+ only, in which case you need latest Babel but actually, if you are targeting only that browser, just remove Babel completely and live happily ever after.

**Comment by MikeVaz** [comment] 2018-05-31 15:38
We are shipping real world apps and we have to support IE11 for next 5-10 years :). Since it is big chunk of our users. 

We don't use babel directly but we use similar approach. I think i published it here in one of the issues.

I tried our current prod code in Chrome 67 without a polyfil and it breaks. Transpiled code breaks too but it is based on v6.x. 

What could happen is If you update this polyfil it might brake the code that worked before. But  new babel version might work with your plugin. And this is what I am trying to verify.

**Comment by WebReflection** [comment] 2018-05-31 16:00
> Transpiled code breaks too but it is based on v6.x.

you need https://github.com/WebReflection/babel-plugin-transform-builtin-classes for Babel 6, that got included in Babel 7.

> It feels like we are the only ones who use this feature in production 

The Google AMP Project (which is also a sponsor of this polyfill) uses it in production too and for long time.

However, you need to follow the README to use the constructor, OR try this latest attempt to fix Babel issues: https://github.com/WebReflection/document-register-element/issues/142#issuecomment-390155176

**Comment by MikeVaz** [comment] 2018-05-31 16:14
I know about Google AMP. Great project BTW. But as far as i know they don't extend built-ins.

**Comment by WebReflection** [comment] 2018-05-31 16:39
@MikeVaz anyway, I don't think talking in here makes any sense, it's just annoying for others that subscribed to this issue which is now fixed.

If you have other issues please open a new one (better if you have code to reproduce issues)
