### ISSUE TITLE
Proposal: fixed user agents

### ISSUE THREAD

**Issue by jpnelson** [WebReflection/document-register-element#86] opened 2016-10-16 23:54 UTC
I have a proposal that I'd like to get thoughts on.

We've had problems in production where browsers implement custom elements and we feature detect this correctly. However, these implementations are often buggy, and fixed in later iterations.

Most notably this happened in Safari 10, but the behaviour is fixed in a later implementation. It has lead us to need to write this hot fix: https://github.com/skatejs/web-components/blob/master/src/fix/safari.js

### Proposal 1

We introduce fixed behaviour based on user agent strings. We would whitelist browser implementations that are "known good" based on a test suite.

The usual problem is, how do we keep on top of this? Browsers are doing stuff all the time, how do we track which implementations are whitelisted?

We would have a test suite that would check to make sure our user agent based testing is equivalent to our feature detection code. When a new browser is released, it would not automatically get native behaviour.

When this new browser is introduced into our tests, if it passes feature detection but is not on the whitelist, this would cause a test failure. We'd then know we need to turn on native behaviour for that browser.

*However*, at that point, we've got the browser in our unit tests, so we'd know if the other tests were failing. This way we can run tests on the new browser before having the native behaviour deployed.

### Proposal 2

Ensure we test against the tech previews of all browsers

I think a little bit more thought needs to be put into proposal 1 as to exactly how it works, but basically I would like to avoid the outcome where a browser vendor releases an update with a buggy implementation and that causes deployed production javascript to start failing.

**Comment by WebReflection** [comment] 2016-10-17 06:48
is this related to this one?
https://github.com/WebReflection/document-register-element/issues/84

if that's the case I might just keep grabbing at runtime `attachShadow`

If not ... I'm not sure I understand how can I help here

**Comment by jpnelson** [comment] 2016-10-17 11:53
It's it's more this type of logic: https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L256

the proposal would be to make this more predictable in production, possibly based on the user agent string instead of pure feature detection.

I'd be interested to hear thoughts about how to make the behaviour more predictable.

**Comment by WebReflection** [comment] 2016-10-17 12:59
I think you might have been mislead by that check which is about `V0` API, the one eventually polyfilled and used to bring `V1` to the same range of target browsers.

The `V1` itself is not so easily feature detected, it's actually more complex than that:
https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L949-L977

There are 3 mode in this polyfill:

  * native, nothing is polyfilled
  * hybrid, Custom Elements are native, builtin extends are polyfilled
  * polyfilled, both Custom Elements and builtins are polyfilled

This is why I am not sure I understand your initial post: is this about this polyfill or something else?

How can this polyfill help solving the problem?

**Comment by WebReflection** [comment] 2016-10-23 10:22
if nothing happens here in a day, I'll close this issue since it's not clear to me what should I do.

**Comment by WebReflection** [comment] 2016-10-25 18:51
like I've said.

**Closed by WebReflection** 2016-10-25 18:51 UTC
Labels: question

**Comment by jpnelson** [comment] 2016-11-02 05:59
yes sorry I was misled regarding that line. It'd be in the area you posted

The problem we have is that we'd like more control over which browsers are getting opted into their native behaviour. For example, Safari at the moment has a buggy implementation of web components, but this is fixed in the technical preview.

It'd be nice if we had the ability to turn on v1 polyfill based not on feature detection, but on user agent. This would make it more predictable.

**Comment by WebReflection** [comment] 2016-11-02 09:20
> It'd be nice if we had the ability to turn on v1 polyfill based not on feature detection, but on user agent. 

this is something everyone can do by itself. You host this polyfill and you decide through your server if the white-listed user agent should get it or not.

Not a polyfill responsibility and on top of that, I believe more in features detection than UA sniffing.

**Comment by jpnelson** [comment] 2016-11-03 12:45
> this is something everyone can do by her/himself. You host this polyfill and you decide through your server if the white-listed user agent should get it or not.

I agree that it should be up to the user to decide when they want the polyfill to be used or not. Would you accept a PR that added that abiltiy? (It'd be a matter of exporting the v1 polyfill function so that we could decide when we want to run it)

**Comment by WebReflection** [comment] 2016-11-03 14:25
> It'd be a matter of exporting the v1 polyfill function so that we could decide when we want to run it

I am not sure I am following here ... so, you are saying you don't want to run the poly but you want to have it included?

Do you know this polyfill uses native CustomElements when these are available and polyfills eventually only the builtins?

**Comment by treshugart** [comment] 2016-11-03 22:39
> Do you know this polyfill uses native CustomElements when these are available and polyfills eventually only the builtins?

I believe what @jpnelson is saying here is that we would like the ability to override the native implementation. The main issue here being WebKit knowingly released a broken Shadow DOM implementation. Now, I know this is their fault, but unfortunately we don't have control over that. We're afraid that they're going to release a broken Custom Elements version as well - or any browser for that matter - and want to ensure our code behaves as normal until we can be sure turning on the native implementation isn't going to hurt anything.

Our consumption might look something like:

```js
import { forcePolyfill } from 'document-register-element';

if (weAreAfraid()) {
  forcePolyfill();
}
```

Alternatively, we can do something like [ShadyDOM](https://github.com/webcomponents/shadydom) does and specify an object before it's loaded:

```js
window.forceCustomElementPolyfill = true;
// load polyfill now
```

That's more difficult to implement in ES6 module-land, but it would still work.

**Comment by WebReflection** [comment] 2016-11-04 09:12
> We're afraid that they're going to release a broken Custom Elements version as well - or any browser for that matter - and want to ensure our code behaves as normal until we can be sure turning on the native implementation isn't going to hurt anything.

But this is indeed why I am saying the feature detection in this polyfill must be reliable enough to grant correct behavior of Custom Elements.

In DOM4 for example I haven't just checked if an element `classList` property is there, I am feature testing at runtime that if I pass more than one class the result is the expected one.

Here I am not assuming if things are there everything is fine, here I am feature testing a whole behavior and patch accordingly.

I'd rather make feature detection more robust than let developers patch browsers forever via UA sniffing **but** I'll try to figure out a way that won't compromise current battle-tested code and can force-patch a browser.

However, whatever it will be it will be an ugly hack against features-detection principle 😞

**Comment by treshugart** [comment] 2016-11-04 13:34
In this case it was the setting of the content of a style node that didn't
trigger a recalc. I understand that you'd rather feature detection this,
but if you can anticipate and write a feature detection for this before it
happens, hats off.

Now, I know that issue is unrelated to your polyfill, but as a result we
have zero confidence at this point that browser vendors won't break
something just as badly with custom elements and it'd be really nice if we
could have control over that.

In thinking about it, we should probably just fork. Less run around and you
don't need to worry about it.

**Comment by WebReflection** [comment] 2016-11-04 14:23
> if you can anticipate and write a feature detection for this before it happens, hats off.

probably not, since IIRC a node needs to be live to trigger attributes changes so the feature would be detected asynchronously => too late


> we have zero confidence at this point that browser vendors won't break

17 years I do this for living, welcome to my world ^_^

This is why I am pushing to improve feature detection, whenever is possible.

Specially because UA sniffing doesn't grant much neither, unless very specific which is hard to have.

A browser sniffed could misbehave or be shadowed forever for no reason.

Remember when IE team started putting weird stuff in its UA to avoid being sniffed VS Chrome?


> In thinking about it, we should probably just fork

it'd be probably better for everyone to find a solution that works everywhere.

If at least I could have a test to fix browsers against, that'd be a start for a patch from my side.

If I read you need UA sniffing and I think that's not the way developers should go when it comes to polyfills, I keep explaining my reasons.

**Comment by WebReflection** [comment] 2016-11-04 14:44
# Possible Work Around

If you sniff the browser that should be force-patched, you know such browser has native `customElements.define` and we could agree on a specific "_feature-test-name_" that would indicate the poly the browser should be force-patched.

```js
// how to unobtrusively specify a force-patch
window.customElements && customElements.define(
  'document-register-element-feature-test',
  HTMLElement
);
```

If we agree on an unobtrusive name used as channel for libraries authors that know what they are doing, I can force polyfill checking that `customElements.get('document-register-element-feature-test')` is not defined or, if it is, forcing the browser to use the poly.

This will make the current code work as it does already, and it will give developers the arbitrary ability to force the polyfill for both custom elements and custom builtins.

From my side it's basically a one liner code change, form your side I don't know how simple it is.

It will be less obtrusive than a global variable on window, and it will work out of the box with or without the polyfill in, reserving a name that nobody would ever use for a custom element, still giving the ability to test if the browser should be force patched passing through the `customElements` namespace it self.

Thoughts?

**Comment by WebReflection** [comment] 2016-11-04 14:52
In case you like the idea, these are three possible reserved names.

Use referenced reactions to vote.

  * 👍for `document-register-element-a` which is [already reserved](https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.node.js#L1404)
  * 🎉for `document-register-element-force-patch` which is more explicit in its intent
  * ❤️for `custom-elements-forced-polyfill` which just came up on my mind

Feel free to down-vote the idea or all names with 👎and eventually write down your name.

I'll start voting my current preference.

**Comment by treshugart** [comment] 2016-11-05 01:42
In your examples, I'm not exactly sure how that'd work. Might just be simpler to export the polyfill as a function. You can then polyfill if it isn't there or we can call it directly to force it.

**Comment by treshugart** [comment] 2016-11-05 01:44
https://github.com/skatejs/named-slots/blob/master/src/index.js

**Comment by treshugart** [comment] 2016-11-05 01:45
Similar to what we do [here](https://github.com/skatejs/named-slots/blob/master/src/index.js) maybe?

**Comment by WebReflection** [comment] 2016-11-05 04:25
Again, this polyfill does **not** just test the presence of V1, it test V1 capabilities and builtins extend. Calling its function only if CE is there isn't enough and if you can feature detect then the poly can too.

My idea works like an event listener would. If you sniff or decide you absolutely want the poly to patch the browser you define upfront an element with the agreed name.

This procedure can be, in your code base, a module a part that includes as dependency this poly and you use such module instead of directly this one, requiring this poly only if needed.

Does this make sense? Would this solve? It should be simple to pre define that CE if you want to force patch. This module already export a function and that's for cross realm as needed by AMP, which is why it cannot export something different.

However, it could add a second parameter that, if true, would force patch the browser. My only concern is that in your case the poly needs to be called twice since it execute itself anyway, which is why I think signaling force-patch upfront is better.

**Comment by WebReflection** [comment] 2016-11-05 05:07
Apparently imports via Babel do not preserve the logical order.

<img width="782" alt="babel-import" src="https://cloud.githubusercontent.com/assets/85749/20027783/5cb5926a-a315-11e6-956b-e92fe6be5bf4.png">

At this point I wonder if a bower alternative module would be appropriate for your use case, but I'm not sure myself that's a good solution anyway.

Will be offline for most of the time this WE and back on Monday, I'll think about something but if you have some other idea please share.

Regards

**Comment by treshugart** [comment] 2016-11-05 08:45
> Apparently imports via Babel do not preserve the logical order.

Imports are supposed to be at the top anyways; interesting the parser didn't throw an error. 

Ultimately, this is up to @jpnelson. I'd like to get his feedback on your proposal. I don't really mind what we come up with as long as we can ensure that we have the ability to override broken implementations or always polyfill and enable native after testing things. Whatever it becomes, it's temporary anyways.

Thanks for your support here. Have a good week :)

**Comment by WebReflection** [comment] 2016-11-05 10:19
..end ;-)
FWIW, I'd like to have reliable features detection instead, even if it means using UA as last resort for inevitably broken cases.

**Comment by jpnelson** [comment] 2016-11-06 20:52
> Might just be simpler to export the polyfill as a function. You can then polyfill if it isn't there or we can call it directly to force it.

After thinking about it, I think it's fair enough to say that you'd get feature detection by default, with the ability for the consumer to have more control if they want it. For that reason I'd be happy if there was a function that we could import that would force the polyfill. Importing that function should have no side effects, and it would export a function that we can call.

I also agree that this is a temporary measure until web components are widely supported / there isn't ongoing development.

Would you consider a pull request that added that?

I also don't think that importing should have side effects generally, as you say, it can become impossible to control ordering of things with es6 imports. That may also be a good reason to provide a function that would force the polyfill. It'd be a breaking change to have no side effects by default, but if there was a different dist file that we could import that exported the function, that would be enough for us.

**Comment by WebReflection** [comment] 2016-11-07 20:55
OK, [ponyfill it is then](https://github.com/WebReflection/document-register-element#new-ponyfill-in-13)

You should `require('document-register-element/pony')` and eventually pass the window object you want to poly and `auto` or `force` as second string argument.

Needless to say `force` will patch regardless both native and builtins extends.

You are in charge now, I hope this solves your use case.

**Comment by oslego** [comment] 2017-08-01 12:06
Here's a use case where you'd want to bypass native support and go on the polyfilled route:

Content scripts from Chrome Extensions are [not allowed to register custom elements](https://bugs.chromium.org/p/chromium/issues/detail?id=390807). As of August 2017, it is till an open issue. It has to deal with the complication of registering custom elements from different isolated worlds (chrome extensions vs host page) in the same scope (the host page DOM). The platform developers have not taken a stance on the expected behaviour yet.

I tried the ponyfill mentioned here and it din't solve the issue. I did not look into why.
I tried the webcomponents [polyfill for custom elements](https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-sd-ce.js), and that worked. Perhaps there's a different strategy used inside for feature detecting.

Not sure if this is replicable in other browsers' extension models, but perhaps this is a good example of a use case for wanting to force the polyfill instead of doing feature detection.

**Comment by WebReflection** [comment] 2017-08-01 12:09
you forgot the code. how did you try this polyfill?
you wrote this? https://github.com/WebReflection/document-register-element#new-ponyfill-in-13

**Comment by oslego** [comment] 2017-08-01 12:17
Yes, I tried that route. I copied the entire source from the [ponyfill](https://github.com/WebReflection/document-register-element/blob/master/pony/index.js) aside from the `module.exports` directly into the content script. 

Then I initialised with `installCustomElements(window, 'force')`. No errors where thrown. 

But trying to do `customElements.define('my-el', MyEl)` after the install, Chrome throws the same error as without the ponyfill, leading me to believe that the ponyfill wasn't used. 

Again, I did not look into why this this is happening. I was just searching for a quick solution to my problem and I found one in the other polyfill. 

Just thought I'd mention the use case here in case it helps clarify why someone might need to bypass native support altogether.

**Comment by oslego** [comment] 2017-08-01 12:26
My apologies, I had not initially noticed that "DO NOT USE DIRECTLY" comment in the ponyfill file.

I tried it again, this time with the indicated file at [document-register-element.node.js](https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.node.js), but I get the same Chrome error.

**Comment by WebReflection** [comment] 2017-08-01 12:38
So, if I take this file and I copy it on a Chrome console:
https://github.com/WebReflection/document-register-element/blob/master/pony/index.js

and I remove the last `module.exports ...` line and write the following instead:
```js
installCustomElements(window, 'force');
```

the global `customElements` object gets replaced by the fully patched polyfill.

I don't know if Chrome extension prevents JS to patch globals, but that's the only guess I have at this point.

Good to know the other polyfill worked, after all this one targets old browsers, not modern extensions.

Too bad googlers haven't simply forced a prefix instead of disabling native CE, not sure I am interested in patching this case (they'll fix before I'll change the code in reliable way for all currently supported platforms).

However, if you find the reason, please let me know, thanks.

**Comment by oslego** [comment] 2017-08-01 13:10
The default Chrome console in DevTools uses the "main world" of the browser so there's no problem there. The "isolated world" granted to the Chrome Extensions is the issue. After install, the polyfill does exist on the global scope (you can patch globals in the "isolated world"), but calling `customElements.define()`,which itself calls `document.registerElement()` at some point, triggers the known Chrome error. 

The other polyfill works out of the box. There's no need to fix this one. I can understand the maintenance overhead and diminishing returns for patching old implementations. Thanks for helping others with your polyfill thus far!

If you're ever interested in diving deeper, I made a [reduced test case](https://github.com/oslego/chrome-extension-custom-element). You can load it as an unpacked Chrome Extension if you check "Developer mode" in chrome://extensions. 

See branch [`alternative`](https://github.com/oslego/chrome-extension-custom-element/tree/alternative) for the example with the `custom-elements-polyfill` and [`master`](https://github.com/oslego/chrome-extension-custom-element/tree/master) for the webcomponents custom elements polyfill. And [a diff](https://github.com/oslego/chrome-extension-custom-element/compare/alternative?expand=1) between the two.

**Comment by WebReflection** [comment] 2017-08-01 14:26
Gotta check if just opting out that fallback when force is used would work, although it would break the initial intent of the ponyfill.

Maybe 'force-all' could work there ... thanks for the info

**Comment by WebReflection** [comment] 2017-08-01 14:57
Do you mind trying [this file](https://github.com/WebReflection/document-register-element/blob/master/pony/index.js) using `installCustomElements(window, 'force-all');` ?

I cannot do that right now but I'm too curious to wait :smile: 

Thanks

**Comment by oslego** [comment] 2017-08-01 15:52
Sadly, this doesn't work either. It actually crashes complaining about the constructor even though I followed the instructions in the README about caveats on calling `super()`. 

    contentscript.js:4 Uncaught TypeError: Illegal constructor
    at MyElement (contentscript.js:4)
    at HTMLElement.value (ponyfill.js:1269)
    at setupNode (ponyfill.js:1167)

Have a look at branch [`alternative-2`](https://github.com/oslego/chrome-extension-custom-element/tree/alternative-2) and a [diff against `master`](https://github.com/oslego/chrome-extension-custom-element/compare/alternative-2?expand=1).

**Comment by WebReflection** [comment] 2017-08-01 16:01
you know what? I'm happy to not fix this but thanks a lot for helping me testing.

I will update the README wit such info.

Cheers

**Comment by oslego** [comment] 2017-08-01 16:02
No problem. Thank you for spending time on it even though you didn't have
to.
