### ISSUE TITLE
Test Fails in FireFox (39.0): constructor (1, 1, 0)

### ISSUE THREAD

**Issue by jlpoolen** [WebReflection/document-register-element#33] opened 2015-07-22 13:24 UTC
Visited this url: http://webreflection.github.io/document-register-element/test/

Results (line "contructor (1, 1, 0)" is in red):

1 Tests Failed
main (2, 0, 0)
as XDirect constructor (3, 0, 0)
as XIndirect constructor (4, 0, 0)
as <x-direct> innerHTML (4, 0, 0)
as <div is="x-indirect"> innerHTML (5, 0, 0)
as createElement(x-direct) (4, 0, 0)
as createElement(div, x-indirect) (5, 0, 0)
attributes (5, 0, 0)
offline (5, 0, 0)
nested (2, 0, 0)
className (5, 0, 0)
registered after (5, 0, 0)
constructor (1, 1, 0)

    unknown

simulating a table element (2, 0, 0)
if registered one way, cannot be registered another way (2, 0, 0)
is="type" is a setup for known extends only (2, 0, 0)
innerHTML helper (1, 0, 0)
innerHTML invoke createdCallback via type (1, 0, 0)
innerHTML invoke createdCallback via extends (1, 0, 0)
innerHTML already registered elements still work (4, 0, 0)
innerHTML with nested elements (2, 0, 0)
innerHTML attributes present on createdCallback (1, 0, 0)
innerHTML attributeChangedCallback (1, 0, 0)

**Comment by WebReflection** [comment] 2015-07-22 14:01
`Mozilla/5.0 (X11; Linux x86_64; rv:39.0) Gecko/20100101 Firefox/39.0` here and everything is green ...

**Comment by jlpoolen** [comment] 2015-07-22 14:04
I'm on Windows 7.

**Comment by WebReflection** [comment] 2015-07-22 14:08
what I am saying is that Firefox in Linux works, Chrome and  Chromium  works, Opera work, even IE on windows work ... I am not sure I want to fix this here, maybe it's a Firefox for Windows bug?

**Comment by jlpoolen** [comment] 2015-07-22 14:11
If there is any more information I can provide you, please let me know.

**Comment by WebReflection** [comment] 2015-07-22 14:13
anyway, it's probably here:
https://github.com/WebReflection/document-register-element/blob/master/test/document-register-element.js#L375-L380

if you could tell me what this returns in your console maybe I can understand what's the issue

```js
var XW = document.registerElement(
  'x-whatever',
  {
    prototype: Object.create(
      HTMLElement.prototype
    )
  }
);

console.log(Object.getPrototypeOf(new XW));
```

thanks

**Comment by WebReflection** [comment] 2015-07-22 14:15
plus

```
new XW instanceof XW // should be true

and

new XW instanceof HTMLElement // should be true
```

thanks

**Comment by WebReflection** [comment] 2015-07-22 14:15
P.S. you need to test in the test page ;-)

**Comment by jlpoolen** [comment] 2015-07-22 14:24
![2015-07-22 07_18_39-document-register-element test](https://cloud.githubusercontent.com/assets/227313/8827616/8db80af6-3042-11e5-838b-ae47dd28f411.png)


![2015-07-22 07_19_44-document-register-element test](https://cloud.githubusercontent.com/assets/227313/8827614/8db0bdd2-3042-11e5-94ef-533fe6fdfe00.png)

![2015-07-22 07_20_48-document-register-element test](https://cloud.githubusercontent.com/assets/227313/8827615/8db4168a-3042-11e5-9ec3-ddd260a6e377.png)

**Comment by WebReflection** [comment] 2015-07-22 14:29
it's OK, you cannot register twice the same element in the same realm / page / window / tab

so , second error is expected

the first one though, is not clear to me

can you please run this exact code after refreshing?

```js
var XW = document.registerElement(
  'x-whatever',
  {
    prototype: Object.create(
      HTMLElement.prototype
    )
  }
);

console.log(
  Object.getPrototypeOf(new XW),
  new XW instanceof XW,
  new XW instanceof HTMLElement
);
```

Thank you

**Comment by jlpoolen** [comment] 2015-07-22 14:32
![2015-07-22 07_31_08-document-register-element test](https://cloud.githubusercontent.com/assets/227313/8827858/dc18a6e6-3043-11e5-985e-efb0054baf8e.png)

**Comment by WebReflection** [comment] 2015-07-22 14:45
I'm afraid we need another test ... bear with me ...

```js
var
  runtime,
  xEl = document.body.appendChild(
    document.createElement('x-el-created')
  ),
  XEL = document.registerElement(
    'x-el-created',
    {
      prototype: Object.create(
        HTMLElement.prototype, {
        createdCallback: {value: function() {
          runtime = this.constructor;
        }}
      })
    }
  )
;

console.log(
  'sync',
  xEl.constructor === runtime,
  xEl instanceof XEL
);

setTimeout(function () {
  console.log(
    'async',
    xEl.constructor === runtime,
    xEl instanceof XEL
  );
}, 1000);
```

Thank you (still try after refreshing)

**Comment by WebReflection** [comment] 2015-07-22 14:46
I've edited there was a typo ...

**Comment by jlpoolen** [comment] 2015-07-22 15:08
![2015-07-22 08_08_04-document-register-element test](https://cloud.githubusercontent.com/assets/227313/8828810/dffcef24-3048-11e5-8d62-3d6b3abe73c0.png)

**Comment by WebReflection** [comment] 2015-07-22 15:12
OK and what the hack is Firefox using as constructor ?

I hope that's not happening because the callback is never invoked 

please update the previus test with this log instead,  thank you (should be last one I ask you)

```
console.log(
  'sync',
  xEl.constructor,
  runtime
);
```

**Comment by jlpoolen** [comment] 2015-07-22 15:15
Don't worry about imposing on me, I'm happy to help.  However, after 9:00 a.m. PDT, I have to answer to a higher authority until 5:00 p.m.

![2015-07-22 08_13_19-document-register-element test](https://cloud.githubusercontent.com/assets/227313/8828991/b90e8462-3049-11e5-8b59-795296e3f20e.png)

**Comment by WebReflection** [comment] 2015-07-22 15:37
you are drunk Firefox, go home!!!

I have honestly a) no idea how that's even possible b) how to test it and c) zero time right now for this, all I can say is that you are not facing a problematic bug, for what I can tell, rather a Firefox on Windows only glitch.

Please remember that is just a test that makes little sense, as it is, and it was meant to simply check that `runtime` was assigned when the `x-whatever` custom element was registered but a node with the same name was already created / /present in the DOM.

Accordingly to these circumstances, the test passes without problem: the callback is invoked, and runtime is indeed not undefined. 

I will leave this open  to better investigate what's going on there, if you can tell me all details about your platform ( like [your UA](http://3site.eu/ua) ) I might try to find a similar setup and either fix the gotcha or change the test.

Thanks for your patience and your understanding.

**Comment by jlpoolen** [comment] 2015-07-22 15:41
http://www.3site.eu/ua
tells me:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0

Also, I closed Firefox and started it again, this time only visiting your test page and got the same result.  I've been working on custom HTML element project in the same session of Friefox and wanted to make sure my code had not interfered.

This test failure has no meaning to me, I just wanted to bring it to your attention so it doesn't bit you later on or it's a flag that something is amiss.

**Comment by WebReflection** [comment] 2015-09-15 10:29
how is this bug doing on FF side? any change?

**Comment by jlpoolen** [comment] 2015-09-15 13:15
Firefox 40.0.3
visiting http://webreflection.github.io/document-register-element/test/
results in 
     1 Tests Failed
     ...
     constructor (1, 1, 0)
     ...

**Comment by WebReflection** [comment] 2015-09-29 20:33
how are we doing with latest Firefox? Mine are still all green!

**Comment by jlpoolen** [comment] 2015-09-29 21:51
Firefox 41.0
visiting http://webreflection.github.io/document-register-element/test/
results in
1 Tests Failed
...
constructor (1, 1, 0)
...

**Comment by WebReflection** [comment] 2015-10-01 09:54
![screenshot from 2015-10-01 11-51-38](https://cloud.githubusercontent.com/assets/85749/10217888/1eb846e2-6833-11e5-82b9-365788655615.png)

**Comment by jlpoolen** [comment] 2015-10-01 13:31
![2015-10-01 06_29_04-greenshot](https://cloud.githubusercontent.com/assets/227313/10221902/06fe8962-6806-11e5-8dad-fb63d2ce5fce.png)

**Comment by WebReflection** [comment] 2015-10-01 14:22
![screenshot from 2015-10-01 11-51-38](https://cloud.githubusercontent.com/assets/85749/10223271/8ab4069a-6858-11e5-92b2-6db257803b61.png)

**Comment by WebReflection** [comment] 2015-10-01 14:22
![screenshot from 2015-10-01 16-19-29](https://cloud.githubusercontent.com/assets/85749/10223297/a4c3645e-6858-11e5-8a1f-16057ff6c4b7.png)

**Comment by WebReflection** [comment] 2015-10-02 05:27
I've pushed the version  `0.5.0` which has a fix for IE10 but I've sneaked in also a change that **might** actually solve that test issue in your Firefox.

Mind checking? Please tell me it's green now ... please!

**Comment by WebReflection** [comment] 2015-10-03 10:00
![ff41_windows_10 wow64](https://cloud.githubusercontent.com/assets/85749/10262414/45f4f644-69c6-11e5-8e7f-64529a62c145.png)


This was on real windows machine

**Comment by WebReflection** [comment] 2015-10-07 22:31
hey @jlpoolen any update after last push?
http://webreflection.github.io/document-register-element/test/

**Comment by jlpoolen** [comment] 2015-10-07 23:31
Still fails at same spot.

**Comment by NekR** [comment] 2015-10-21 13:05
Everything is green for me. Maybe it's worth disabling all the extensions/addons before the test? Knowing how  Firefox extensions works, there is a good chance that one of them is a causer of this issue.

**Comment by WebReflection** [comment] 2015-10-21 13:30
Actually @jlpoolen if you can tell me which extensions are you running I'll stick a bloody **WARNING THIS EXTENSION SUCK** in the README ... thanks!

**Comment by jlpoolen** [comment] 2015-10-21 14:18
I went into "Tools->Add-ons" and disabled *all* of my extensions.  I restarted Firefox, confirmed all extensions were disabled.  Then went to your test.  Same result, alas.  I do have plug-ins such as Google Talk Plugin, but have not set them to "Never Activate".  I do have a Firebug, is there something I could do to debug or provide debugging output?

![2015-10-21 07_11_41-about mozilla firefox](https://cloud.githubusercontent.com/assets/227313/10639127/5bb67dda-77c3-11e5-8a39-40fe3b88f6eb.png)

**Comment by WebReflection** [comment] 2015-10-21 14:30
can you drop Firebug and let me know how that goes? I wouldn't be surprised ... 

Otherwise every machine, native or VM, I could possibly try, 32 or 64 bit, Windows **any version**, plus any other person  I could ask .. won't have this problem, meaning I might just close this until I am able to reproduce it.

**Comment by jlpoolen** [comment] 2015-10-21 14:45
what do you mean by "drop"?  I had and have Firebug disengaged:
![2015-10-21 07_44_04-add-ons manager](https://cloud.githubusercontent.com/assets/227313/10639986/a985ed62-77c7-11e5-8ee2-8daf19f0f576.png)

**Comment by WebReflection** [comment] 2015-10-21 14:50
so everything is disabled and only you on this planet have this problem. Can you find any other computer around you that shows the same issue?

**Comment by jlpoolen** [comment] 2015-10-21 16:33
I tried it from another Windows 7 and got a 100% pass.

**Comment by WebReflection** [comment] 2015-10-26 17:02
I'm going to close this until I'm able to reproduce or you are able to reproduce in another machine.

Hope this won't cause any trouble to you when using real-world services based on this  poly.

**Closed by WebReflection** 2015-10-26 17:02 UTC
