### ISSUE TITLE
connectedCallback runs before init directly after calling HTMLElement's constructor by super

### ISSUE THREAD

**Issue by AndyOGo** [WebReflection/document-register-element#154] opened 2018-10-25 11:11 UTC
Unfortunately he suggested workaround within the your readme [**Skipping the caveat through `extends`**](https://github.com/WebReflection/document-register-element#skipping-the-caveat-through-extends) does not work.

**Expected** (like in Chrome - not polyfilled):
1. call `constructor()`
2. forward to `HTMLElement`'s `constructor` by `super` and keep that context
3. now call `init()` with proper context
4. `connectCallback()` triggers somewhen after `init()`

**Actual** (polyfilled browser like Firefox 62):
1. call `constructor()`
2. forward to `HTMLElement`'s `constructor` by `super` and keep that context
3. `connectCallback()` triggers immediately after above `super` is called
4. unfortunately this call of `init()` is too late now

**Clarification**:

This does not happen in Chrome.
It happens only in Firefox, which actually uses this polyfill.

**Comment by WebReflection** [comment] 2018-10-25 11:50
there is literally nothing I can do if the browser invokes `connectedCallback` when `super()` is called, but that would be new to me.

Which browser are you using?

The alternative is using a semaphore to delay `connectedCallback` or `attributeChangedCallback` but until I have some code to test that confirms your issue I don't even know what to suggest.

**Comment by AndyOGo** [comment] 2018-10-25 11:55
Thanks for your quick answer.

Sorry I did not made my point clear.
If I use Chrome without the polyfill everything works as expected. As soon as I switch to Firefox which needs this polyfill, it breaks 😞

**Comment by WebReflection** [comment] 2018-10-25 11:59
I don't have any code to test. The day I will have the most basic way to reproduce what you are saying, is the only day I can eventually help.

**Comment by AndyOGo** [comment] 2018-10-25 12:05
Agreed.

I'm currently evaluating alternatives to the [official custom-elements polyfill](https://github.com/webcomponents/custom-elements) mainly because it lacks support of built-in elements.

So I created a PR with actually both issue I just files - hope you have easy access:
https://github.com/axa-ch/patterns-library/pull/642

**Comment by WebReflection** [comment] 2018-10-25 12:08
here, as example ... 
https://codepen.io/WebReflection/pen/vVvKjB

this shows init and connected for both cases. Which Firefox version doesn't ?

P.S. **this** is the official custom-elements-polyfill, if anything ... this is the most deployed polyfill in the real world, including AFrame and Google AMP Project, and Stencil JS, etcetera.

Where did you get that _official_ information ? Their description says:

> A polyfill for HTML Custom Elements v1

**not** the official polyfill.

Please don't count Github stars to name things official, thanks.

**Comment by WebReflection** [comment] 2018-10-25 12:20
I am closing this since I'm unable to reproduce.

Remember to put the polyfill before anything else or you're causing troubles to your own code.

No shim upfront, no polyfills upfront, let it be by its own.

If you need custom elements builtins, also consider doing [what's described in this post](https://hackernoon.com/extending-built-in-elements-9dce404b75b4) so that only old browsers or Edge will bring in the polyfill, and others can use the < 1K patch (Safari) while Firefox 63+ and Chrome won't be affected at all.

<img width="1381" alt="screen shot 2018-10-25 at 14 17 38" src="https://user-images.githubusercontent.com/85749/47499666-cd711380-d860-11e8-8a94-d2e35ab4d8c0.png">

**Comment by AndyOGo** [comment] 2018-10-25 12:21
Thanks for that link.

This example indeed works as expected, though it's a simple case, without any nested custom elements.
I use latest Firefox version `62`.

Please let me explain how how this happens:
I have multiple custom elements one **nested** within the other. Know the main issue is the asynchronous characteristic of custom elements, which means:
- a child could call `connectedCallback` before it's parent
- and a parent could call it before it's children
- any other combination is possible too

Now `connectedCallback` bubbles, which causes this bug.



^^Alright. Yours is the official.
Well I named it "official" mainly because they own the best naming for:
- their webiste https://www.webcomponents.org
- the github organization: https://github.com/webcomponents

**Closed by WebReflection** 2018-10-25 12:20 UTC

**Comment by AndyOGo** [comment] 2018-10-25 12:37
Great, you are right, we agree that `connectedCallback` has nothing todo with the `constructor`.
Anyway I observed the above buggy behaviour.

Alright, did I offend you in any way by saying "Web components" or "official"?

> 19+ here
> yet Google AMP sponsors and uses this polyfill
That is awesome, congratulations

> but it looks like in filing bugs you still should stretch yourself to provide valuable informations and reproducible code
Alright. I have provided the exact observation I made in my browser. I agree that reproducible code is a big win - so I linked my open PR.

I appreciate that your take your time and I thanks you for your feedback.

I have also some honest feedback for you.
Please work on improving your social skills, don't feel offended if I mention another project, let people contribute and help you achieving your awesome work.

Have a nice day.

**Comment by WebReflection** [comment] 2018-10-25 12:58
> I agree that reproducible code is a big win - so I linked my open PR.

I am a full time employee with not so much time to dig into external repositories.

If you could create a code pen with the minimal amount of code that demonstrate the bug I'll try to help as I can.

>  let people contribute

if they manage to

> and help you achieving your awesome work.

I'm offering support with a very limited amount of time. When you'll help me in helping you everything will work just fine.

**Comment by AndyOGo** [comment] 2018-10-25 13:07
Thanks you very much for your quick answer.

> I am a full time employee with not so much time to dig into external repositories.

Totally understood. I have the same problem.

Okay, I will try to find some time to extract a reduced reproducible test case without the project I'm currently working on.

**Comment by AndyOGo** [comment] 2018-10-25 13:43
I hope this helps you better and gives you all the data you need #157
