### ISSUE TITLE
Refreshing a document inside an iframe which loads d-r-e breaks the polyfill and leaves document.createElement as undefined

### ISSUE THREAD

**Issue by franktopel** [WebReflection/document-register-element#175] opened 2019-08-13 12:31 UTC
When document-register-element is loaded in a document which is inside an iframe, refreshing that iframe breaks the polyfill and makes it so `document.createElement` is `undefined`.

Demo repository: https://github.com/franktopel/iframe-ie11-document-register-element

**Comment by WebReflection** [comment] 2019-08-13 12:39
can you please try with fully qualified CDN name as in `https://unpkg.com/document-register-element@1.14.1/build/document-register-element.js` ? it looks like unpkg is having issues, with any browser

**Comment by franktopel** [comment] 2019-08-13 12:49
Done. Problem remains the same. Is also the same on our real product where we import the script from `node_modules` and run it through webpack.

**Comment by WebReflection** [comment] 2019-08-13 12:52
I can reproduce, yes. This is super messed up ... apparently IE loses its core definitions on iframe reloads, I've no idea if I can even fix this, but I'll try when I'll have time.

**Comment by franktopel** [comment] 2019-08-13 15:27
Not sure, but could this be related? https://javascript.info/cross-window-communication#iframe-wrong-document-pitfall

**Comment by WebReflection** [comment] 2019-08-13 16:19
no, it's the usual IE11 BS; thy this code and read `undefined` after 5 seconds.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
    console.log(document.createElement);
    document.createElement = function () {};
    setTimeout(function () { location.reload(true); }, 5000);
    </script>
</body>
</html>
```

**Comment by WebReflection** [comment] 2019-08-13 16:23
It should've been fixed with `1.14.2` ... thanks gosh it was deadly simple to patch

**Comment by franktopel** [comment] 2019-08-13 17:55
Will give it a ride in the office tomorrow and let you know how it went. Thanks for caring!

**Comment by franktopel** [comment] 2019-08-14 08:48
Can your describe the problem and how you addressed it? I assume this can be relevant for alot of polyfill code. Maybe as a section "polyfilling caveats with IE11 and iframes" in your readme.md?

**Comment by WebReflection** [comment] 2019-08-14 09:05
> Can your describe the problem and how you addressed it?

**Problem** if you overwrite a host object method within an iframe, when such iframe reloads such method won't be the inherited one, but undefined instead.

Minimal steps to reproduce in IE11 using this file as iframe content:
```js
<!DOCTYPE html>
<script>
console.log(document.createElement);
document.createElement = function () {};
setTimeout(function () { location.reload(true); }, 5000);
</script>
```

> I assume this can be relevant for alot of polyfill code.

They don't talk to me, not sure I should talk to them.

> Maybe as a section "polyfilling caveats with IE11 and iframes" in your readme.md?

Not really, as there's no caveat, since the poly provides a solution already, so there's nothing to be worried about.

> Or as a separate blog post?

I've [already twitted about it](https://twitter.com/WebReflection/status/1161338822065643520), there's not much to add, IMO (and if they don't follow me, they won't read my blog post neither).

Because of your follow up, I am assuming you are also confirming the issue has been solved though, so thanks for coming back.

**Comment by franktopel** [comment] 2019-08-14 11:27
Unfortunately your fix only works for the **first** refresh. Immediately refresh again, and `document.createElement` again is `undefined`. Additionally it throws an `Object expected` error in the console:

![grafik](https://user-images.githubusercontent.com/10668603/63017657-3466c400-be97-11e9-99f9-f672ea9793d9.png)

**Comment by WebReflection** [comment] 2019-08-14 14:23
This is not what I am experiencing. This is the exact code, used as iframe of your repo example.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <script>
    console.log(document.createElement);
    document.createElement = function () {};
    setTimeout(function () { location.reload(true); }, 5000);
    addEventListener('beforeunload', function () { delete document.createElement; }, false);
    </script>
</body>
</html>

```

![Screenshot from 2019-08-14 16-22-31](https://user-images.githubusercontent.com/85749/63028856-db575a00-beaf-11e9-9909-3d8edbfbb403.png)

**Comment by franktopel** [comment] 2019-08-14 15:17
Your example does not involve your polyfill. If I had to guess I'd go with your polyfill probably not being executed due to the necessity checks on iframe refresh, and thus, the event listener for `beforeunload` not being added? Did you even check with my repository code?

**Comment by WebReflection** [comment] 2019-08-14 15:21
I thought you had those issues with the minimal reproducible code I've provided, while you meant the poly fails, and I've probably tested too quickly and _hoorrayed_ too soon.

Will have a look later on today, the fix will be the same regardless, but the listener added at the beginning of each check, instead of at the end, dropping all patches in there (I thought it was just one, maybe it's more).

**Closed** 2019-08-14 20:05 UTC

**Comment by WebReflection** [comment] 2019-08-14 20:07
OK, I've double checked this time, and everything seems to be fine.

Please let me know if that's not the case.

If you are curious about what's the difference now, basically I delete also `document.importNode` and `document.registerElement` so that next frame reload won't have any sort of issue.

**Comment by franktopel** [comment] 2019-08-15 11:39
Thanks alot for your lightning fast reaction times. I can confirm that both in the MVCE as well as in our application the error does no longer occur.

Good job!
