### ISSUE TITLE
error ""Failed to construct 'HTMLElement': Please use the 'new' operator"" when using with Angular/elements 8.2.0

### ISSUE THREAD

**Issue by rudolfolah** [WebReflection/document-register-element#174] opened 2019-08-04 16:20 UTC
This issue was reported previously on Angular's project page: https://github.com/angular/angular/issues/24556

Essentially they are using any version that is between 1.7.2 and the latest. The latest versions of document-register-element are no longer working and are resulting in this error message:

```
"Failed to construct 'HTMLElement': Please use the 'new' operator"
```

I ran through the different packages to find the latest *working* version:

To test this I changed the package version to the exact version, ran `npm install`, and then ran `ng serve --prod` to see if the error showed up again.

The [document-register-element package versions](https://github.com/WebReflection/document-register-element/releases) tried:

| version | worked? |
|---------|---------|
| 1.14.1 | no |
| 1.14.0 | no |
| ... | (assuming no versions between worked) |
| 1.10.1 | no |
| 1.10.0 | no |
| 1.9.2 | no |
| 1.9.1 | no |
| 1.9.0 | no |
| 1.8.1 | yes |
| 1.8.0 | yes |
| 1.7.2 | yes |

So [something changed between 1.8.1 and 1.9.0 that causes the error](https://github.com/WebReflection/document-register-element/compare/v1.8.1...v1.9.0).

**Comment by MikeVaz** [comment] 2019-08-05 14:28
I believe the problem is how you transpile your ES2015 code in ES5 code. 

```
Transpilers VS 1.9
The version 1.9 of this polyfill does not patch browsers with full native support for Custom Elements, as anyone would expect from a polyfill based on features detection.

However, if your transpiler transforms native ES2015 classes into something incompatible, like TypeScript does in this case, you need to update, change, or better configure your tools to support proper classes.

Babel 7 should've solved this in core, so use Babel 7 if you need transpilers.
```

I would try to compare what is used in this angular module to deal with ES classes. Is it transpiled by Typescript or is it trying to do something custom to mimic classes.  If it is a custom solution you'd probably want to fix it by apply the same pattern from Babel 7 to reflect ES classes in ES5 syntax better.

**Comment by WebReflection** [comment] 2019-08-08 12:07
1.9 indeed doesn't care about broken transpilers do this is a won't fix.

You can use older versions from CDNs or update your transpiler or create bundles for modern browsers without transpiling classes.

**Closed by WebReflection** 2019-08-08 12:07 UTC
