### ISSUE TITLE
Element constructor produces incorrect is attribute and doesn't call attachedCallback in Firefox

### ISSUE THREAD

**Issue by rconnamacher** [WebReflection/document-register-element#22] opened 2015-05-22 22:49 UTC
Creating elements by constructor incorrectly produces an `is` attribute and doesn't call `attachedCallback` in Firefox. (It works correctly in Safari, and I didn't test IE.)

    var ctor = document.registerElement("my-element", {});
    new ctor();

produces `<my-element></my-element>` in Safari, but `<my element is="false"></my-element>` in Firefox. After some digging, this is because the constructor returned by `document.registerElement` calls `document.createElement("my-element", false)` in Firefox, and that false argument is then stringified into the `is` attribute.

More seriously, the bad `is` attribute causes `attachedCallback` to never fire.

Tested in document-register-element 4.0 and Firefox 37-38. (I checked the tests, and there don't appear to be any unit tests covering constructors or attachedCallback.)

**Comment by WebReflection** [comment] 2015-05-25 09:56
I cannot reproduce this on platforms that use this polyfill ... are you sure that's not rather a Firefox bug?

What you are doing is tested all over here: http://webreflection.github.io/document-register-element/test/

plus you are creating an element without any prototype, which attribute/attached should fire?

I need an exact test case to move on, the one you provided is already tested and AFAICT no browser add is attribute as false anywhere.

**Comment by WebReflection** [comment] 2015-05-25 09:58
actually ... never mind, I can reproduce indeed in firefox ... WTF, I'll fix it asap

**Comment by WebReflection** [comment] 2015-05-25 10:06
fixed on `0.4.1`, apologies for any inconvenience

**Closed by WebReflection** 2015-05-25 10:06 UTC
Labels: bug

**Comment by rconnamacher** [comment] 2015-05-26 17:24
Thanks for the speedy fix, it's working here now too.
